name: 'Setup Az-Acme CLI'
description: 'Setup Az-Acme CLI on GitHub Actions runner'
branding:
  icon: award
  color: blue
inputs:
  version:
    description: Version of CLI to install
    required: false
    default: 0.1-beta
runs:
  using: node12
  main: dist/index.js
