name: Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            binary: az-acme
          - kind: windows
            os: windows-latest
            binary: az-acme.exe
          - kind: macOS
            os: macos-latest
            binary: az-acme
        version: [0.1-beta]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup CLI
      uses: ./
      with:
        version: ${{ matrix.version }}

    - name: Run
      run: |
        ${{ matrix.binary }} --version